// CABEÇA

export const VERIFY_CONDITION_HEAD_SUCCESS = "VERIFY_CONDITION__HEAD_SUCCESS";
export const VERIFY_CONDITION_HEAD_FAILURE = "VERIFY_CONDITION__HEAD_FAILURE";

// BRAÇO ESQUERDO
export const VERIFY_CONDITION_ARM_LEFT_SUCCESS =
  "VERIFY_CONDITION_ARM_LEFT_SUCCESS";
export const VERIFY_CONDITION_ARM_LEFT_FAILURE =
  "VERIFY_CONDITION_ARM_LEFT_FAILURE";

// BRAÇO DIREITO

export const VERIFY_CONDITION_ARM_RIGHT_SUCCESS =
  "VERIFY_CONDITION_ARM_RIGHT_SUCCESS";
export const VERIFY_CONDITION_ARM_RIGHT_FAILURE =
  "VERIFY_CONDITION_ARM_RIGHT_FAILURE";
